name: Linting Compliance

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest #18.04LTS
    name: Checking compliance
    steps: 
      - name: Checkout Head
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          
      - name: Check Linting Compliance
        run: yarn lint
      
