name: Linting Compliance

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest #18.04LTS
    name: Checking compliance
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.push.head.sha }}
          
      - name: Check for scripts
        run: cat package.json
      
