# This is a basic workflow to help you get started with Actions

name: Linting Compliance

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest #18.04LTS
    name: Checking compliance
    steps: 
      - name: Checkout Latest
        uses: actions/checkout@v2
        
      - name: Check linting
        run: echo $PWD
      
