name: Linting Compliance

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest #18.04LTS
    name: Checking compliance
    steps: 
      - name: Checkout Latest
        uses: actions/checkout@v2
      
      - name: Lint Check
        run: cat package.json
      
